# Generated by Django 5.1.5 on 2026-07-06 22:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=16, unique=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("centroid", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
                ),
                ("floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("water_notes", models.CharField(blank=True, default="", max_length=255)),
                ("power_notes", models.CharField(blank=True, default="", max_length=255)),
                ("security_notes", models.CharField(blank=True, default="", max_length=255)),
                ("parking", models.BooleanField(default=False)),
                ("caretaker_name", models.CharField(blank=True, default="", max_length=120)),
                ("caretaker_phone", models.CharField(blank=True, default="", max_length=16)),
                ("has_active_vacancy", models.BooleanField(db_index=True, default=False)),
                ("is_demoted", models.BooleanField(db_index=True, default=False)),
                ("latest_verified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_by_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buildings",
                        to="core.agent",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to="core.estate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="coverage",
            field=models.ManyToManyField(blank=True, related_name="agents", to="core.estate"),
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BEDSITTER", "Bedsitter"),
                            ("1BR", "1 Bedroom"),
                            ("2BR", "2 Bedroom"),
                            ("3BR", "3 Bedroom"),
                            ("SINGLE", "Single Room"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rent_kes", models.PositiveIntegerField()),
                ("deposit_kes", models.PositiveIntegerField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=dict)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_types",
                        to="core.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=16)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="core.building",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="core.unittype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("storage_key", models.CharField(max_length=512)),
                ("thumbnail_key", models.CharField(blank=True, default="", max_length=512)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.building",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.unittype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VacancySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("vacant_count", models.PositiveSmallIntegerField()),
                ("verified_at", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AGENT_VISIT", "Agent visit"),
                            ("CARETAKER_CALL", "Caretaker call"),
                            ("CARETAKER_SELF_REPORT", "Caretaker self-report"),
                        ],
                        default="AGENT_VISIT",
                        max_length=24,
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.unittype",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="unittype",
            constraint=models.UniqueConstraint(
                fields=("building", "kind"), name="uniq_unit_type_per_building"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancysnapshot",
            index=models.Index(
                fields=["unit_type", "-verified_at"], name="core_vacanc_unit_ty_1288db_idx"
            ),
        ),
    ]
